### ISSUE TITLE
Error building ufront-iso

### ISSUE THREAD

**Issue by MichaPooh** [cambiata/ufront-iso#2]
When I try to build the ufront-iso application I get the following error:

D:\Projects\Haxe\web\ufront-iso-master>ufront build
Build build.hxml
C:\HaxeToolkit\haxe\lib/ufront-mvc/1,0,0-rc,9/src/ufront/api/UFApi.hx:121: lines
 121-201 : Missing return tink.Surprise<_makeApiCall.A, haxe.remoting.RemotingEr
ror<_makeApiCall.B>>
Failed to build build.hxml

It is not really an issue with your application I guess (which is a very good example by the way),
but I have no idea where that comes from (I am using the code from the repo as it is)

**Comment by cambiata** [comment]
Hi Micha!

I guess that this is caused by changes in the latest ufront-mvc releases.
But the example doesn't use UFApi at all, so you could do a dirty one and try to add a "return null;" in the method that causes the problem...

**Comment by MichaPooh** [comment]
Hello again,

Actually I was thinking that as well, so it tried to set the ufront-mvc version to rc.9  (before I used the latest rc.17), the one you use as well according to your README. (but i've got with the same error with both)
In my understanding this should work because new releases would not affect the rc.9, or am I wrong?

The only place I've found UFApi is used is in the UfrontConfiguration when it is merged with DefaultUfrontConfiguration and than it gets extremely complicated to understand what's going on:
I find myself digging into ApiMacros.hx code etc.

Just adding "return null" to the function where the error occurs inside the "#elseif client" directive 
(it happens only for the client build) don't change anything .

Again, that is not an issue with your app, thanks already for your answer you gave,
but I just don't get what's the error with my setup. 
When you can compile your app with a certain setup of libraries, I should be able to as well.

**Comment by MichaPooh** [comment]
Actually I am able to build:
I had to change all #if Client directives to #if client (lowercase) 
and now it works :)

I have absolutely no idea why I actually tried it with lowercase
(I guess some kinda desperately subconscious action), 
because I didn't thought it could have anything to do with the compiler directives.

but I am happy I did....
