### ISSUE TITLE
Porting to php

### ISSUE THREAD

**Issue by MichaPooh** [cambiata/ufront-iso#3]
Hello

I have a bit of weird behaviour when I export the project to php on my localhost.
Actually it works in general as expected (loading the content or refreshing clicking 'no pushstate' etc.) , 
just every time the application loads from the cache it updates the 'load-type' with 'page refresh'
and doesn't update the link clicked. 
So it seems that there is a refresh of any kind what I don't understand because it should update only the inner HTML via ClientResponse flush method....

First i thought it might have something to do with the .htaccess which I added and which should do the same thing as the rewrite flag for neko server:
```
<ifModule mod_rewrite.c>
Options +FollowSymLinks
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
#RewriteCond %{REQUEST_URI} !index
RewriteRule (.*) index.php [L]
</ifModule>
```

some traces I added  when for example /info is clicked (and  loaded from the cache):
```
"Trace: MainController.loadContent(66): MainController::loadContent -> client:/info" 
"Trace: MainController.loadContent(74): got cache for /info" 
"Trace: ClientResponse.flush(97): ClientResponse::flush" 
"Trace: Iso.setUI(17): Try update menu:/contact" <-----   ???? (shows the same when running on nekoserver though)
"Trace: Main.main(24): PushState::function:http://localhost/info" 
"Trace: ClientResponse.new(91): ClientResponse:new" 
"Trace: ClientRequest.get_uri(78): ClientRequest::get_uri:/info" 
"Trace: IsoResult.getContent(38): IsoResult::getContent"
```

Do you have any ideas for that behaviour?
Can it have something to do with Pushstate or the HTTPContext when exporting for PHP?
(the very same code works perfectly when building for neko - I just change the 
-neko bin/index.n to -php C:\wamp\www and the -js export location in build.hxml )

all the best

**Comment by cambiata** [comment]
Hi Micha!

I'm afraid that I can't help you here - I haven't touched php for years...
Also, Jason has done some isometric updates to Ufront, have you seen that? https://github.com/ufront/hello/commit/083ea8a8a844d7c221bcbaca0e90f91bdcfb4ddc
I'm sure that he has a lot more clever solutions than my hackish experiments...

**Comment by MichaPooh** [comment]
Hi Jonas, no worries...
I gonna take a look at Jasons isometic example...
I was sticking with your example because it's a little neat one 
(what is nice when one is trying to get his head around how ufront is working :) )
